### ISSUE TITLE
Things seems to be broken

### ISSUE THREAD

**Issue by linusblom** [chas-academy/09-recipe-book-jonastore#2]
Images are not displaying (an extra http in url) and when clicking on a recipe the page turns blank.
![cors](https://user-images.githubusercontent.com/22654895/37141414-2a24561c-22b5-11e8-966b-2fe8cfe55c53.jpeg)

**Comment by jonastore** [comment]
I'll get right on to the image issue. Although I only managed to get the detail view to work in the 10-recipe-app assignment.

**Comment by linusblom** [comment]
I can test this in the 10-recipe-app if you would like, since 10 is depending on 9 I can test them together? If that makes it easier?

**Comment by jonastore** [comment]
That makes a lot of sense and would be great, thanks!

torsdag 8 mars 2018 skrev Linus Blom <notifications@github.com>:
